import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Mono, Julius_Sans_One, Alex_Brush, Oleo_Script, Caveat_Brush } from "next/font/google";
import './globals.css';
import './payloadStyles.css';
import Navbar from "../components/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-robotoMono",
  subsets: ["latin"],
})
const julius = Julius_Sans_One({
  variable: "--font-julius",
    subsets: ["latin"],
    weight: "400",
})
const alexBrush = Alex_Brush({
  variable: "--font-alexBrush",
  subsets: ["latin"],
  weight: "400",
})
const oleoScript = Oleo_Script({
  variable: "--font-oleoScript",
  subsets: ["latin"],
  weight: "400",
})
const caveatBrush = Caveat_Brush({
  variable: "--font-caveatBrush",
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>  ) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${robotoMono.variable} 
          ${julius.variable} 
          ${alexBrush.variable}
          ${oleoScript.variable}  
          ${caveatBrush.variable}
          
          antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
