import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Mono, Julius_Sans_One, Alex_Brush, Oleo_Script, Caveat_Brush, Quicksand, Karla, M_PLUS_Rounded_1c, Nunito, Playfair_Display, Cookie, Style_Script } from "next/font/google";
import './globals.css';
import './payloadStyles.css';
import Nav from "./components/nav/Nav";
import Footer from "./components/Footer";
import { Analytics } from '@vercel/analytics/next';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-robotoMono",
  subsets: ["latin"],
})
const julius = Julius_Sans_One({
  variable: "--font-julius",
    subsets: ["latin"],
    weight: "400",
})
const alexBrush = Alex_Brush({
  variable: "--font-alexBrush",
  subsets: ["latin"],
  weight: "400",
})
const oleoScript = Oleo_Script({
  variable: "--font-oleoScript",
  subsets: ["latin"],
  weight: "400",
})
const caveatBrush = Caveat_Brush({
  variable: "--font-caveatBrush",
  subsets: ["latin"],
  weight: "400",
})

const quickSand = Quicksand({
  variable: "--font-quickSand",
  subsets: ["latin"],
  weight: "400"
})
const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
  weight: "400"
})
const mPlusRound = M_PLUS_Rounded_1c({
  variable: "--font-mPlusRound",
  subsets: ["latin"],
  weight: "400"
})

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "500"],
})

const playfairDisplay = Playfair_Display({
  variable: "--font-playfairDisplay",
  subsets: ["latin"],
  weight: ["400", "500"],
})

const cookie = Cookie({
  variable: "--font-cookie",
  subsets: ["latin"],
  weight: ["400"],
})

const styleScript = Style_Script({
  variable: "--font-styleScript",
  subsets: ["latin"],
  weight: ["400"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>  ) {
  return (
    <html lang="en"  className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${robotoMono.variable} 
          ${julius.variable} 
          ${alexBrush.variable}
          ${oleoScript.variable}  
          ${caveatBrush.variable}
          ${quickSand.variable}
          ${karla.variable}
          ${mPlusRound.variable}
          ${nunito.variable}
          ${playfairDisplay.variable}
          ${cookie.variable}
          ${styleScript.variable}
          antialiased   `}>
      <body className={" min-w-full "}>
        <Nav />
        <main className="bg-warmBeige min-w-full h-full text-cuteBlue font-quickSand ">
          {children}
        </main>
        <Analytics/>
         <Footer/> 
      </body>
    </html>
  );
}
